server:
  port: 8080

spring:
  application:
    name: genai-ollama-demo

  ai:
    ollama:
      base-url: http://localhost:11434 #
      chat:
        options:
          model: llama3.2                #
          temperature: 0.3               #
      init:
        pull-model-strategy: when_missing # Pulls model on app boot if missing